#!/bin/bash

# Check if the correct number of arguments are provided
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 COMMAND RESOURCE_TYPE NAMESPACE "
    exit 1
fi

# Define command-line arguments
COMMAND=$1
RESOURCE_TYPE=$2
NAMESPACE=$3

# Retrieve resource usage statistics from Kubernetes
kubectl $COMMAND $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read -r NAME CPU MEMORY
do
  # Output the statistics to the console
  echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
done